# Site settings
title: Anonymous Blog
email: dalmavong@gmail.com
description: "wang,15年会毕业于zju.接触过Android,Sencha Touch,WP开发,目前从事iOS开发工作.初期喜欢泛而广大而全的开发经验,实习面试时被虐惨,现阶段专精iOS."
baseurl: ""
url: "http://wangnull.github.io/"

# Build settings
markdown: rdiscount
permalink: pretty
pygments: true
